apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: kserve-agent-29
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhoai-tenant/kserve-agent/kserve-agent-29@sha256:7a1ad2f6abeb77b3331ec472f272956e41a5c90b36af9b5f96536d3ebb14b3e9
        name: container-image
        resources: {}
status: {}
