apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: kserve-agent-28
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: kserve-agent-28
    app.kubernetes.io/part-of: kserve-agent
  name: kserve-agent-28
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: kserve-agent-28
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: kserve-agent-28
    spec:
      containers:
      - image: quay.io/modh/kserve-agent@sha256:5cdea9e02b5ebfa74da3aa10b662ae05f40393d71db76cdd77d2856b93fa2fff
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 256Mi
status: {}
